In [0]:
import numpy as np

a = np.array([-3,2,5])
b = np.array([1,2,4])

Soal nomor 1

---



In [5]:
c = a+b
print(c)

[-2  4  9]


Soal nomor 2

In [6]:
d = 2*a
print(d)

[-6  4 10]


Soal nomor 3

In [8]:
e = b/2
print(e)

[0.5 1.  2. ]


soal nomor 4 (dot product)

In [9]:
f = np.dot(a,b)
print(f)

21


soal nomor 5 (cross product)

In [10]:
g = np.cross(a,b)
print(g)

[-2 17 -8]
